import sharp from 'sharp';
import fs from 'fs/promises';
import path from 'path';
import { encodeToKTX2 } from 'ktx2-encoder';
import * as thumbhash from 'thumbhash';

const INPUT_DIR = 'src/assets/images';
const PUBLIC_TEXTURES_DIR = 'public/textures';
const PUBLIC_OPTIMIZED_DIR = 'public/optimized';
const METADATA_FILE = 'src/data/portfolio-metadata.ts';
const TARGET_RES = 1024;

async function ensureDir(dir: string) {
  try {
    await fs.access(dir);
  } catch {
    await fs.mkdir(dir, { recursive: true });
  }
}

async function generateThumbHash(imagePath: string) {
  const { data, info } = await sharp(imagePath)
    .resize(100, 100, { fit: 'inside' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  
  const hash = thumbhash.rgbaToThumbHash(info.width, info.height, data);
  return Buffer.from(hash).toString('base64');
}

async function optimizeImage(filename: string) {
  const inputPath = path.join(INPUT_DIR, filename);
  const baseName = path.parse(filename).name;
  
  console.log(`Optimizing ${filename}...`);

  const image = sharp(inputPath);
  
  // 1. Generate AVIF for DOM/Mobile fallback
  const avifPath = path.join(PUBLIC_OPTIMIZED_DIR, `${baseName}.avif`);
  await image
    .resize(TARGET_RES, TARGET_RES, { fit: 'inside', withoutEnlargement: true })
    .avif({ quality: 55, effort: 6 })
    .toFile(avifPath);

  // 2. Generate KTX2 using library (no CLI needed)
  const ktxPath = path.join(PUBLIC_TEXTURES_DIR, `${baseName}.ktx2`);
  
  try {
    // Get raw RGBA for the encoder
    const metadata = await image.metadata();
    const width = metadata.width || 1024;
    const height = metadata.height || 1024;

    // Calculate clamped dimensions (multiple of 4 for KTX2)
    const scale = Math.min(1, TARGET_RES / Math.max(width, height));
    const finalW = Math.floor((width * scale) / 4) * 4;
    const finalH = Math.floor((height * scale) / 4) * 4;

    const { data, info } = await image
      .resize(finalW, finalH, { fit: 'fill' })
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });

    // Node-specific encoder call
    const ktxBuffer = await encodeToKTX2(data, {
      width: info.width,
      height: info.height,
      etc1s: true, // Switch to ETC1S for massive space savings (90% smaller)
      qualityLevel: 128, // High quality ETC1S
      mipmaps: true,
      imageDecoder: async (buf) => ({
        data: buf,
        width: info.width,
        height: info.height
      })
    });

    await fs.writeFile(ktxPath, ktxBuffer);
  } catch (err) {
    console.error(`Failed to encode KTX2 for ${filename}:`, err);
  }

  // 3. Generate ThumbHash
  const tHash = await generateThumbHash(inputPath);

  const finalMetadata = await image.metadata();

  return {
    id: baseName,
    width: finalMetadata.width,
    height: finalMetadata.height,
    ktx2: `/textures/${baseName}.ktx2`,
    avif: `/optimized/${baseName}.avif`,
    thumbHash: tHash
  };
}

async function main() {
  await ensureDir(PUBLIC_TEXTURES_DIR);
  await ensureDir(PUBLIC_OPTIMIZED_DIR);

  const files = (await fs.readdir(INPUT_DIR)).filter(f => 
    f.startsWith('portfolio-') && (f.endsWith('.jpg') || f.endsWith('.png') || f.endsWith('.jpeg'))
  );

  const results: Record<string, any> = {};
  
  for (const file of files) {
    const meta = await optimizeImage(file);
    results[meta.id] = meta;
  }

  const tsContent = `/**
 * AUTO-GENERATED PORTFOLIO METADATA
 * Generated by scripts/optimize-assets.ts
 */
export const portfolioMetadata: Record<string, {
  ktx2: string;
  avif: string;
  width: number;
  height: number;
  thumbHash: string;
}> = ${JSON.stringify(results, null, 2)};
`;

  await fs.writeFile(METADATA_FILE, tsContent);
  console.log(`Metadata written to ${METADATA_FILE}`);
}

main().catch(console.error);
