/**
 * AUTO-GENERATED PORTFOLIO METADATA
 * Generated by scripts/optimize-assets.ts
 */
export const portfolioMetadata: Record<string, {
  ktx2: string;
  avif: string;
  width: number;
  height: number;
  thumbHash: string;
}> = {
  "portfolio-1": {
    "id": "portfolio-1",
    "width": 1500,
    "height": 2000,
    "ktx2": "/textures/portfolio-1.ktx2",
    "avif": "/optimized/portfolio-1.avif",
    "thumbHash": "ETkKFQSYeH93eHZId4aYeJlvlvlm"
  },
  "portfolio-2": {
    "id": "portfolio-2",
    "width": 1333,
    "height": 2000,
    "ktx2": "/textures/portfolio-2.ktx2",
    "avif": "/optimized/portfolio-2.avif",
    "thumbHash": "1hcOFQaQZ312eHd4d4Wnhg1r45IH"
  },
  "portfolio-3": {
    "id": "portfolio-3",
    "width": 2000,
    "height": 1333,
    "ktx2": "/textures/portfolio-3.ktx2",
    "avif": "/optimized/portfolio-3.avif",
    "thumbHash": "USgODYSDVYlvaJeUh2d4dzuvovVI"
  },
  "portfolio-4": {
    "id": "portfolio-4",
    "width": 2000,
    "height": 1333,
    "ktx2": "/textures/portfolio-4.ktx2",
    "avif": "/optimized/portfolio-4.avif",
    "thumbHash": "kBgODYJwV3qKhoikd1iJhiBqccIH"
  },
  "portfolio-5": {
    "id": "portfolio-5",
    "width": 1170,
    "height": 1453,
    "ktx2": "/textures/portfolio-5.ktx2",
    "avif": "/optimized/portfolio-5.avif",
    "thumbHash": "SxgGDgIMQ3m3nAWYt7hneneGaIZQdgg="
  },
  "portfolio-6": {
    "id": "portfolio-6",
    "width": 567,
    "height": 423,
    "ktx2": "/textures/portfolio-6.ktx2",
    "avif": "/optimized/portfolio-6.avif",
    "thumbHash": "0wcKBYA/hUVSinZTd4iIVU9k5TEH"
  },
  "portfolio-7": {
    "id": "portfolio-7",
    "width": 567,
    "height": 423,
    "ktx2": "/textures/portfolio-7.ktx2",
    "avif": "/optimized/portfolio-7.avif",
    "thumbHash": "V1YGDYTXPHAgorqAammHaybgCUw3"
  },
  "portfolio-8": {
    "id": "portfolio-8",
    "width": 567,
    "height": 423,
    "ktx2": "/textures/portfolio-8.ktx2",
    "avif": "/optimized/portfolio-8.avif",
    "thumbHash": "1TcOFYRAhXlvWJd4eIeHd0vAB5h3"
  }
};
